FROM node:22-alpine AS builder
WORKDIR /app
COPY ../client/package*.json ./
RUN npm install
COPY ../client/ .
RUN npm run build

FROM nginx:stable-alpine AS runner
COPY --from=builder /app/dist /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 4173
CMD ["nginx", "-g", "daemon off;"]
